In [1]:
import tensorflow as tf

In [2]:
aa = tf.exp(2.0)
bb = tf.add(aa, 1.)
cc = tf.sqrt(bb)
print(cc)

tf.Tensor(2.8963869, shape=(), dtype=float32)


In [16]:
@tf.function
def func(inp):
    aa = tf.exp(inp)
    print(aa)
    bb = tf.add(aa, 1.)
    print(bb)
    cc = tf.sqrt(bb)
    print(cc)
    return cc
print(func(tf.constant(2.0, dtype=tf.float32)))
print(func(tf.constant(1.0, dtype=tf.float32)))


Tensor("Exp:0", shape=(), dtype=float32)
Tensor("Add:0", shape=(), dtype=float32)
Tensor("Sqrt:0", shape=(), dtype=float32)
tf.Tensor(2.8963869, shape=(), dtype=float32)
tf.Tensor(1.9282846, shape=(), dtype=float32)


In [7]:
def func(inp):
    aa = tf.exp(inp)
    print(aa)
    bb = tf.add(aa, 1.)
    print(bb)
    cc = tf.sqrt(bb)
    print(cc)
    return cc
print(func(2.0))

tf.Tensor(7.389056, shape=(), dtype=float32)
tf.Tensor(8.389056, shape=(), dtype=float32)
tf.Tensor(2.8963869, shape=(), dtype=float32)
tf.Tensor(2.8963869, shape=(), dtype=float32)


In [ ]:
with tf.Graph().as_default():
    aa = tf.exp(2.0)
    print(aa)
    bb = tf.add(aa, 1.)
    print(bb)
    cc = tf.sqrt(bb)
    print(cc)

## Take Gradient of a Variable

In [39]:
#take gradient of a variable
def func(w):
    aa = tf.exp(w)
    bb = tf.add(aa, 1.)
    cc = tf.sqrt(bb)
    return cc

w = tf.Variable(2.0, dtype=tf.float32)

with tf.GradientTape() as tape:
    y = func(w)
print(tape.gradient(y, w))

tf.Tensor(1.2755646, shape=(), dtype=float32)


## Gradient Tape watch

In [43]:
# take gradient of a non-variable
def func(inp):
    aa = tf.exp(inp)
    bb = tf.add(aa, 1.)
    cc = tf.sqrt(bb)
    return cc

with tf.GradientTape() as tape:
    inp = tf.constant(2.0, dtype=tf.float32)
    tape.watch(inp)
    inp1 = inp*2
    inp2 = inp1**2
    out = func(inp2)
    print(tape.gradient(out, inp1))

tf.Tensor(11923.831, shape=(), dtype=float32)


In [18]:
# @tf.function
def func():
    aa = tf.Variable(1.0, dtype=tf.float32)
    bb = tf.Variable(2.0, dtype=tf.float32)
    print(aa, bb)
print(func())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
None


In [10]:
aa = tf.Variable(2.0)
print(aa)
aa.assign(3.0)
print(aa)
aa.assign_add(2.0)
print(aa)
aa.assign_sub(1.0)
print(aa)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>


In [ ]:
@tf.function
def func(inp):
    aa = tf.exp(inp)
    bb = tf.add(aa, 1.)
    cc = tf.sqrt(bb)
    return cc

In [2]:
aa = [1, 2, 3, 4]
bb = [1, 3, 4, 'hello']
cc = [aa, bb, 34]
print(aa)
print(bb)
print(cc)

print(len(aa))
print(len(bb))
print(len(cc))

[1, 2, 3, 4]
[1, 3, 4, 'hello']
[[1, 2, 3, 4], [1, 3, 4, 'hello'], 34]
4
4
3


In [3]:
aa = [1, 2, 3, 4]
bb = [1, 3, 4, 'hello']
cc = [aa, bb, 34]
print(aa)
print(bb)
print(cc)
print(cc[2]) # print cc 中的最后一个元素
cc[2]='there'
print(cc)

[1, 2, 3, 4]
[1, 3, 4, 'hello']
[[1, 2, 3, 4], [1, 3, 4, 'hello'], 34]
34
[[1, 2, 3, 4], [1, 3, 4, 'hello'], 'there']


In [9]:
aa = [1, 2, 3, 4, 5, 6]
bb = [o+0.2 for o in aa]
print(aa)
print(aa[2:5]) #slice 第二号到第四号元素，也是一个list
print(bb)

[1, 2, 3, 4, 5, 6]
[3, 4, 5]
[1.2, 2.2, 3.2, 4.2, 5.2, 6.2]


In [18]:
aa = 'hello, how are you doing'
print(aa)
print(aa[1:4])

print('how' in aa)
print('hodw' in aa)

print(aa.find('how'))
print(' '.join(['asdf', 'iouon']))

hello, how are you doing
ell
True
False
7
asdf iouon


In [23]:
aa = {'key': 'value', 2: 'there', 'key2':'hello'}
print(aa)
print(aa['key'])
print(aa[2])

{'key': 'value', 2: 'there', 'key2': 'hello'}
value
there


In [24]:
aa = (1, 2, 4, 5)
print(aa)
print(aa[:3])

(1, 2, 4, 5)
(1, 2, 4)


In [33]:
aa = 'hello, how'
s = 'how'
if s in aa:
    print('"%s" is in the string'%s)
else:
    print('"%s" not in the string'%s)
    
print('=='*10)
for i in aa:
    print(i)

"how" is in the string
h
e
l
l
o
,
 
h
o
w


In [47]:
def func(aa):
    print(f'hello, this is func, argument is {aa}')
    ret = aa +'word'
    return ret

In [48]:
ret = func('hello ')
print(ret)

hello, this is func, argument is hello 
hello word


In [57]:
class B:
    def __init__(self):
        self.bvar = 0.2

class A(B):
    def __init__(self):
        super(A, self).__init__()
        self.var = 0
        
    def func(self):
        self.var +=1
    def __call__(self):
        self.var+=2

aa = A()
for i in range(5):
    aa.func()
    print(aa.var)
print('--'*5)
for i in range(5):
    aa()
    print(aa.var)
print('--'*5)
print(aa.bvar)


1
2
3
4
5
----------
7
9
11
13
15
----------
0.2


In [19]:
aa = range(10)
print(aa)
print('=='*5)
print([i for i in range(10)])

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [35]:
arr1 = np.random.rand(4, 4)
print(arr1)
print('--'*10)
print(np.transpose(arr1))
print('--'*10)
inv_arr1 = np.linalg.inv(arr1)
print(inv_arr1)
print('--'*10)
print(np.dot(arr1, inv_arr1))


[[0.30046073 0.22540455 0.35071192 0.08742732]
 [0.32245581 0.48066222 0.94634912 0.9820427 ]
 [0.19283751 0.8807215  0.92611392 0.62253314]
 [0.73793292 0.1877469  0.7334378  0.77869074]]
--------------------
[[0.30046073 0.32245581 0.19283751 0.73793292]
 [0.22540455 0.48066222 0.8807215  0.1877469 ]
 [0.35071192 0.94634912 0.92611392 0.7334378 ]
 [0.08742732 0.9820427  0.62253314 0.77869074]]
--------------------
[[-1.76312223 -3.32082472  1.60157797  3.10559922]
 [-5.19538803 -4.73282826  4.40146347  3.03329846]
 [ 9.11153887  6.29619103 -4.64981382 -5.24606558]
 [-5.65855334 -1.64217284  1.80062625  2.55100826]]
--------------------
[[ 1.00000000e+00 -2.40017707e-17  1.27019883e-16 -2.91570978e-16]
 [-3.98476466e-16  1.00000000e+00 -4.69247668e-17 -3.37207919e-16]
 [-9.90276656e-17 -2.92502341e-16  1.00000000e+00  5.18605237e-17]
 [ 1.23260543e-16  4.33118071e-16  2.50008338e-16  1.00000000e+00]]


In [38]:
#假设A矩阵的shape是[2, 3, 4]
#   B矩阵的shape是[3, 4]
#假设要做按位加法操作那么B会被自动广播成[1，3，4]进而变成[2, 3, 4]，然后就可以操作了
A = np.arange(24).reshape(2, 3, 4)
print(A)
print('=='*5)
B = np.arange(12).reshape(3, 4)
print(B)
print('=='*5)
print(A+B)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]


In [1]:
import tensorflow as tf

In [2]:
tf.sequence_mask([1, 3, 5, 6, 7], maxlen=5)

<tf.Tensor: id=8, shape=(5, 5), dtype=bool, numpy=
array([[ True, False, False, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>